name: Mirror to GitLab

on:
  push:
    branches: ['**']
    tags: ['**']
  delete: {}
  workflow_dispatch: {}

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add GitLab remote
        run: |
          CLEAN_REMOTE="${{ secrets.GITLAB_REMOTE#https:// }}"
          git remote add gitlab "https://oauth2:${{ secrets.GITLAB_TOKEN }}@${CLEAN_REMOTE}"
          git remote -v

      - name: Push all refs (mirror)
        run: |
          git push --prune --mirror gitlab
